services: 

  limesurvey:
    image: mazurkatarzyna/cwe-79-limesurvey-ex4:latest
    ports:
      - 127.0.0.1:9094:80
    environment:
      LIMESURVEY_DB_PASSWORD: e/xa|m|ple
      LIMESURVEY_ADMIN_USER: admin
      LIMESURVEY_ADMIN_PASSWORD: password
      LIMESURVEY_ADMIN_NAME: Lime Administrator
      LIMESURVEY_ADMIN_EMAIL: lime@lime.lime
      TZ: Europe/London
    volumes:
      - ./plugins:/var/www/html/plugins
      - ./upload:/var/www/html/upload
      - ./config:/var/www/html/application/config
      - ./sessions:/var/lime/sessions

  mysql:
    image: mazurkatarzyna/cwe-79-mariadb-ex4:latest
    environment:
      MYSQL_ROOT_PASSWORD: e/xa|m|ple
    volumes:
       - ./mysql:/var/lib/mysql

